version: "3.8"

services:
  backend:
    build:
      context: ./backend
    dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      NODE_ENV: production
    restart: always

  frontend:
    build:
      context: ./frontend
    dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app
    environment:
      NODE_ENV: production
    restart: always
